export type HskLevel = 1 | 2 | 3;

export type HskCharacter = {
  hanzi: string;
  pinyin: string;
  meaningSv: string;
  level: HskLevel;
  pedagogyHint: string;
  exampleWord: string;
};

export const HSK_1_TO_3_CHARACTERS: HskCharacter[] = [
  // HSK 1
  {
    hanzi: "我",
    pinyin: "wǒ",
    meaningSv: "jag / mig",
    level: 1,
    pedagogyHint: "Skriv långsamt: vänster hand-radikal först, sedan höger del.",
    exampleWord: "我们 (wǒmen) = vi",
  },
  {
    hanzi: "你",
    pinyin: "nǐ",
    meaningSv: "du",
    level: 1,
    pedagogyHint: "Människoradikalen 亻 till vänster hjälper dig minnas pronomen.",
    exampleWord: "你好 (nǐhǎo) = hej",
  },
  {
    hanzi: "他",
    pinyin: "tā",
    meaningSv: "han",
    level: 1,
    pedagogyHint: "Bygg som 你: person-radikal först, sedan den högra delen.",
    exampleWord: "他们 (tāmen) = de",
  },
  {
    hanzi: "人",
    pinyin: "rén",
    meaningSv: "människa",
    level: 1,
    pedagogyHint: "Två enkla streck med tydlig balans mellan vänster och höger.",
    exampleWord: "中国人 (Zhōngguórén) = kines",
  },
  {
    hanzi: "口",
    pinyin: "kǒu",
    meaningSv: "mun",
    level: 1,
    pedagogyHint: "Följ en fyrkant i rätt ordning: vänster, topp+höger, botten.",
    exampleWord: "人口 (rénkǒu) = befolkning",
  },
  {
    hanzi: "日",
    pinyin: "rì",
    meaningSv: "sol / dag",
    level: 1,
    pedagogyHint: "Yttre ram först, inre horisontellt streck i mitten.",
    exampleWord: "生日 (shēngrì) = födelsedag",
  },
  {
    hanzi: "月",
    pinyin: "yuè",
    meaningSv: "måne / månad",
    level: 1,
    pedagogyHint: "Låt vänster lodrätt streck leda rytmen innan de inre strecken.",
    exampleWord: "月亮 (yuèliang) = måne",
  },
  {
    hanzi: "大",
    pinyin: "dà",
    meaningSv: "stor",
    level: 1,
    pedagogyHint: "Toppstrecket först, sedan vänster och höger ben.",
    exampleWord: "大学 (dàxué) = universitet",
  },
  {
    hanzi: "小",
    pinyin: "xiǎo",
    meaningSv: "liten",
    level: 1,
    pedagogyHint: "Mittenstreck först, sidostreck därefter för symmetri.",
    exampleWord: "小学 (xiǎoxué) = grundskola",
  },
  {
    hanzi: "山",
    pinyin: "shān",
    meaningSv: "berg",
    level: 1,
    pedagogyHint: "Mittenpelaren ger höjd; sidopelare avslutar tecknets form.",
    exampleWord: "火山 (huǒshān) = vulkan",
  },
  {
    hanzi: "水",
    pinyin: "shuǐ",
    meaningSv: "vatten",
    level: 1,
    pedagogyHint: "Mitten först, sedan de flytande sidostrecken.",
    exampleWord: "水果 (shuǐguǒ) = frukt",
  },
  {
    hanzi: "火",
    pinyin: "huǒ",
    meaningSv: "eld",
    level: 1,
    pedagogyHint: "Börja mitt i tecknet och låt sidostrecken flamma ut.",
    exampleWord: "火车 (huǒchē) = tåg",
  },
  {
    hanzi: "木",
    pinyin: "mù",
    meaningSv: "träd / trä",
    level: 1,
    pedagogyHint: "Horisontellt streck först, lodrätt genom mitten, sedan grenarna.",
    exampleWord: "木头 (mùtou) = trä",
  },
  {
    hanzi: "中",
    pinyin: "zhōng",
    meaningSv: "mitten",
    level: 1,
    pedagogyHint: "Ramen först, mittstrecket sist för tydlig centrering.",
    exampleWord: "中国 (Zhōngguó) = Kina",
  },
  {
    hanzi: "国",
    pinyin: "guó",
    meaningSv: "land / nation",
    level: 1,
    pedagogyHint: "Yttre ram omfamnar inre komponenten i lugn takt.",
    exampleWord: "国家 (guójiā) = stat",
  },
  {
    hanzi: "好",
    pinyin: "hǎo",
    meaningSv: "bra",
    level: 1,
    pedagogyHint: "Kvinna-radikal 女 först, sedan 子 till höger.",
    exampleWord: "好吃 (hǎochī) = gott",
  },
  {
    hanzi: "学",
    pinyin: "xué",
    meaningSv: "lära / studera",
    level: 1,
    pedagogyHint: "Toppen skrivs i flera små steg innan barn-tecknet 子.",
    exampleWord: "学生 (xuésheng) = elev",
  },
  {
    hanzi: "生",
    pinyin: "shēng",
    meaningSv: "födas / liv",
    level: 1,
    pedagogyHint: "Håll nederdelen stabil så tecknet står stadigt.",
    exampleWord: "先生 (xiānsheng) = herr",
  },
  {
    hanzi: "天",
    pinyin: "tiān",
    meaningSv: "himmel / dag",
    level: 1,
    pedagogyHint: "Kort toppstreck först, sedan stor kropp likt 大.",
    exampleWord: "今天 (jīntiān) = idag",
  },
  {
    hanzi: "气",
    pinyin: "qì",
    meaningSv: "luft / energi",
    level: 1,
    pedagogyHint: "Skriv med lätt hand: formen ska kännas som rörelse.",
    exampleWord: "天气 (tiānqì) = väder",
  },

  // HSK 2
  {
    hanzi: "家",
    pinyin: "jiā",
    meaningSv: "hem / familj",
    level: 2,
    pedagogyHint: "Tak-radikalen 宀 ger struktur innan underdelen skrivs.",
    exampleWord: "回家 (huíjiā) = gå hem",
  },
  {
    hanzi: "友",
    pinyin: "yǒu",
    meaningSv: "vän",
    level: 2,
    pedagogyHint: "Bygg vänster-del först, sedan höger i mjuk båge.",
    exampleWord: "朋友 (péngyou) = vän",
  },
  {
    hanzi: "电",
    pinyin: "diàn",
    meaningSv: "el",
    level: 2,
    pedagogyHint: "Liknar 日 med en krokad avslutning i nederdelen.",
    exampleWord: "电脑 (diànnǎo) = dator",
  },
  {
    hanzi: "话",
    pinyin: "huà",
    meaningSv: "tal / ord",
    level: 2,
    pedagogyHint: "Tal-radikalen 讠 skrivs alltid före högerdelen.",
    exampleWord: "说话 (shuōhuà) = prata",
  },
  {
    hanzi: "书",
    pinyin: "shū",
    meaningSv: "bok",
    level: 2,
    pedagogyHint: "Ett fåtal streck men tydlig ordning ger ren form.",
    exampleWord: "看书 (kànshū) = läsa bok",
  },
  {
    hanzi: "车",
    pinyin: "chē",
    meaningSv: "fordon",
    level: 2,
    pedagogyHint: "Mittenlinjen håller hela tecknet samman.",
    exampleWord: "汽车 (qìchē) = bil",
  },
  {
    hanzi: "时",
    pinyin: "shí",
    meaningSv: "tid",
    level: 2,
    pedagogyHint: "Dag-radikal 日 till vänster, tempodel till höger.",
    exampleWord: "时间 (shíjiān) = tid",
  },
  {
    hanzi: "间",
    pinyin: "jiān",
    meaningSv: "mellanrum / tid",
    level: 2,
    pedagogyHint: "Dörr-radikal 门 omsluter innehållet i kontrollerad ordning.",
    exampleWord: "房间 (fángjiān) = rum",
  },
  {
    hanzi: "吃",
    pinyin: "chī",
    meaningSv: "äta",
    level: 2,
    pedagogyHint: "Mun-radikal 口 först, handlingen till höger därefter.",
    exampleWord: "吃饭 (chīfàn) = äta mat",
  },
  {
    hanzi: "喝",
    pinyin: "hē",
    meaningSv: "dricka",
    level: 2,
    pedagogyHint: "Mun-radikal först även här; jämför med 吃 för minnet.",
    exampleWord: "喝水 (hēshuǐ) = dricka vatten",
  },
  {
    hanzi: "买",
    pinyin: "mǎi",
    meaningSv: "köpa",
    level: 2,
    pedagogyHint: "Övre del först, sedan nedre streck i tydlig sekvens.",
    exampleWord: "买东西 (mǎidōngxi) = köpa saker",
  },
  {
    hanzi: "看",
    pinyin: "kàn",
    meaningSv: "se / titta",
    level: 2,
    pedagogyHint: "Hand-formen ovanför öga-radikal hjälper betydelsen.",
    exampleWord: "看见 (kànjiàn) = se",
  },
  {
    hanzi: "说",
    pinyin: "shuō",
    meaningSv: "säga",
    level: 2,
    pedagogyHint: "Tal-radikal 讠 först; håll högerdelen kompakt.",
    exampleWord: "小说 (xiǎoshuō) = roman",
  },
  {
    hanzi: "听",
    pinyin: "tīng",
    meaningSv: "lyssna",
    level: 2,
    pedagogyHint: "Mun-radikal kopplas till hörande genom uppmärksam rytm.",
    exampleWord: "听见 (tīngjiàn) = höra",
  },
  {
    hanzi: "写",
    pinyin: "xiě",
    meaningSv: "skriva",
    level: 2,
    pedagogyHint: "Takdelen först, sedan underdelen med tydlig slutpunkt.",
    exampleWord: "写字 (xiězì) = skriva tecken",
  },
  {
    hanzi: "读",
    pinyin: "dú",
    meaningSv: "läsa",
    level: 2,
    pedagogyHint: "Tal-radikal leder in till högerdelen; tänk högläsning.",
    exampleWord: "读书 (dúshū) = läsa",
  },
  {
    hanzi: "医",
    pinyin: "yī",
    meaningSv: "medicin / läkare",
    level: 2,
    pedagogyHint: "Yttre struktur först, inre del i kontrollerade steg.",
    exampleWord: "医生 (yīshēng) = läkare",
  },
  {
    hanzi: "院",
    pinyin: "yuàn",
    meaningSv: "institution / gård",
    level: 2,
    pedagogyHint: "Vänster sidradikal 阝 först, sedan högerdelen.",
    exampleWord: "医院 (yīyuàn) = sjukhus",
  },
  {
    hanzi: "店",
    pinyin: "diàn",
    meaningSv: "butik",
    level: 2,
    pedagogyHint: "Takradikal 广 skapar ramen för inre tecken.",
    exampleWord: "商店 (shāngdiàn) = affär",
  },
  {
    hanzi: "衣",
    pinyin: "yī",
    meaningSv: "kläder",
    level: 2,
    pedagogyHint: "Övre strecken först, sedan hängande nederdel.",
    exampleWord: "衣服 (yīfu) = kläder",
  },

  // HSK 3
  {
    hanzi: "班",
    pinyin: "bān",
    meaningSv: "klass / skift",
    level: 3,
    pedagogyHint: "Skriv vänsterdel och högerdel i jämn balans.",
    exampleWord: "班级 (bānjí) = klass",
  },
  {
    hanzi: "级",
    pinyin: "jí",
    meaningSv: "nivå / grad",
    level: 3,
    pedagogyHint: "Silke-radikal 纟 till vänster först, sedan högerdelen.",
    exampleWord: "高级 (gāojí) = avancerad",
  },
  {
    hanzi: "题",
    pinyin: "tí",
    meaningSv: "fråga / ämne",
    level: 3,
    pedagogyHint: "Mer komplext tecken: dela upp i små rytmiska block.",
    exampleWord: "问题 (wèntí) = fråga/problem",
  },
  {
    hanzi: "意",
    pinyin: "yì",
    meaningSv: "mening / avsikt",
    level: 3,
    pedagogyHint: "Övre del först, hjärtelement 心 sist för betydelsekoppling.",
    exampleWord: "意思 (yìsi) = betydelse",
  },
  {
    hanzi: "思",
    pinyin: "sī",
    meaningSv: "tänka",
    level: 3,
    pedagogyHint: "Fältet 田 först, hjärta 心 därefter: tanke + känsla.",
    exampleWord: "思考 (sīkǎo) = tänka",
  },
  {
    hanzi: "帮",
    pinyin: "bāng",
    meaningSv: "hjälpa",
    level: 3,
    pedagogyHint: "Vänster-delens ordning är nyckeln innan höger komponent.",
    exampleWord: "帮助 (bāngzhù) = hjälp",
  },
  {
    hanzi: "准",
    pinyin: "zhǔn",
    meaningSv: "korrekt / punktlig",
    level: 3,
    pedagogyHint: "Vattenradikal 冫 först; högerdelen kräver lugn sekvens.",
    exampleWord: "准备 (zhǔnbèi) = förbereda",
  },
  {
    hanzi: "备",
    pinyin: "bèi",
    meaningSv: "förbereda / redo",
    level: 3,
    pedagogyHint: "Skriv överdelen lätt och låt underdelen stabilisera.",
    exampleWord: "准备好 (zhǔnbèihǎo) = färdig",
  },
  {
    hanzi: "因",
    pinyin: "yīn",
    meaningSv: "orsak",
    level: 3,
    pedagogyHint: "Yttre ruta först, inre 大 i rätt ordning.",
    exampleWord: "因为 (yīnwèi) = eftersom",
  },
  {
    hanzi: "为",
    pinyin: "wèi",
    meaningSv: "för / att vara",
    level: 3,
    pedagogyHint: "Kort men lurigt tecken, följ varje streck medvetet.",
    exampleWord: "为什么 (wèishénme) = varför",
  },
  {
    hanzi: "希",
    pinyin: "xī",
    meaningSv: "hoppas",
    level: 3,
    pedagogyHint: "Överdelen först, därefter tyg-liknande nederdel.",
    exampleWord: "希望 (xīwàng) = hopp",
  },
  {
    hanzi: "望",
    pinyin: "wàng",
    meaningSv: "hopp / blicka",
    level: 3,
    pedagogyHint: "Många streck: dela i tre visuella block för minne.",
    exampleWord: "希望 (xīwàng) = hoppas",
  },
  {
    hanzi: "已",
    pinyin: "yǐ",
    meaningSv: "redan",
    level: 3,
    pedagogyHint: "Komprimera formen; sista böjen avgör tecknets karaktär.",
    exampleWord: "已经 (yǐjīng) = redan",
  },
  {
    hanzi: "经",
    pinyin: "jīng",
    meaningSv: "passera / redan",
    level: 3,
    pedagogyHint: "Silke-radikal först, sedan högerdelen i tydlig rytm.",
    exampleWord: "已经 (yǐjīng) = redan",
  },
  {
    hanzi: "比",
    pinyin: "bǐ",
    meaningSv: "jämföra",
    level: 3,
    pedagogyHint: "Skriv vänster och höger i kontrast för att minnas betydelsen.",
    exampleWord: "比较 (bǐjiào) = jämförelse",
  },
  {
    hanzi: "较",
    pinyin: "jiào",
    meaningSv: "relativt / jämförelse",
    level: 3,
    pedagogyHint: "Bil-radikal 车 först, sedan högerdelen.",
    exampleWord: "比较 (bǐjiào) = jämföra",
  },
  {
    hanzi: "真",
    pinyin: "zhēn",
    meaningSv: "sann / verklig",
    level: 3,
    pedagogyHint: "Överdelen och underdelen måste hållas proportionerliga.",
    exampleWord: "真的 (zhēnde) = verkligen",
  },
  {
    hanzi: "旅",
    pinyin: "lǚ",
    meaningSv: "resa",
    level: 3,
    pedagogyHint: "Flagg-liknande vänsterdel först, sedan högerdelens detaljer.",
    exampleWord: "旅游 (lǚyóu) = resa",
  },
  {
    hanzi: "游",
    pinyin: "yóu",
    meaningSv: "resa / simma",
    level: 3,
    pedagogyHint: "Vattenradikal 氵 först; resten i lugna block.",
    exampleWord: "旅游 (lǚyóu) = turism",
  },
  {
    hanzi: "公",
    pinyin: "gōng",
    meaningSv: "offentlig / allmän",
    level: 3,
    pedagogyHint: "Överdelen först, underdelen bygger en tydlig bas.",
    exampleWord: "公司 (gōngsī) = företag",
  },
];

export function filterCharactersByLevels(
  selectedLevels: HskLevel[]
): HskCharacter[] {
  return HSK_1_TO_3_CHARACTERS.filter((entry) =>
    selectedLevels.includes(entry.level)
  );
}
